# Generated by Django 4.2 on 2025-04-16 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_student_coinhistory_alter_adminprofile_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(max_length=14, null=True),
        ),
    ]
