# Generated by Django 4.2 on 2025-04-03 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_adminprofile_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('manager', 'Manager'), ('accountant', 'Accountant'), ('teacher', 'Teacher'), ('pupil', 'Pupil')], default='manager', max_length=30),
        ),
    ]
