# Generated by Django 4.2 on 2025-04-02 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='distict',
            new_name='district',
        ),
    ]
