# Generated by Django 4.2 on 2025-04-02 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_rename_distict_school_district'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='school',
            options={'verbose_name': 'School', 'verbose_name_plural': 'Schools'},
        ),
        migrations.AlterField(
            model_name='school',
            name='district',
            field=models.CharField(blank=True, choices=[], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='region',
            field=models.CharField(choices=[('Andijon', 'Andijon'), ('Buxoro', 'Buxoro'), ("Farg'ona", "Farg'ona"), ('Jizzax', 'Jizzax'), ('Xorazm', 'Xorazm'), ('Namangan', 'Namangan'), ('Navoiy', 'Navoiy'), ('Qashqadaryo', 'Qashqadaryo'), ('Qoraqalpog‘iston', 'Qoraqalpog‘iston'), ('Samarqand', 'Samarqand'), ('Sirdaryo', 'Sirdaryo'), ('Surxondaryo', 'Surxondaryo'), ('Toshkent', 'Toshkent')], default='Jizzax', max_length=100),
        ),
    ]
